### ISSUE TITLE
Units in ECU response telegram

### ISSUE THREAD

**Issue by towe96** [stprograms/SuperSoco485Monitor#6]
Hi! I'm currently building a new dashboard app based on the SuSoDevs one and your project.
I've found that bytes 1 and 2 in the 0xAADA message (Current drawn by the controller) have the unit 0.1A; e.g. `(Byte1 * 256 + Byte2) / 10` is the current drawn in Amps.
Likewise for bytes 3 and 4 (Speed of the bike), it's around 0.028 km/h steps (`(Byte3 * 256 + Byte 4) * 0.028` km/h) according to my comparison with GPS speeds. That's close enough that it might just be steps of 0.01 m/s.

Some other deviations I've found:
I believe byte 2 in the telegram is the destination of the telegram and byte 3 is the source, opposite to what's in the readme file.
On my bike, data byte 9 in the BMS telegram says "0" when discharging and "1" when charging, but that might also be different between models - mine is a 2020 TC Max.
As for the other pins on the 4-pin connector, Pin 1 is a brake signal used to prevent movement when the charger is plugged in, Pin 4 is ground. Pin 2 is RS-485 A, pin 3 is RS-485 B

I'll soon check how setting different "Speed Meter Coeffs" in the controller programming will influence that. I'd been experimenting with that value for a bit to try and get rid of the speedometers inaccuracy, but it didn't seem to have an effect on its accuracy - so I assume it also wouldn't change the speed transmitted on the bus which I assume the speedometer uses for its display.
The speedometer seems to update faster than the 3-4 ECU telegrams per second I'm seeing on the bus, but that might just be an interpolation done within the speedometer itself.

**Comment by stprograms** [comment]
Hi @towe96!
Thank you very much for your interest and your findings, I really appreciate it :-) 
Regarding the charging: that really seems to depend on the model. I have verified that on my TC Max (2021 / 2022) and for my model, the state is valid.

Could you please create a branch, add your findings and issue a pull request? That would be great and we are sure that I understood your findings correctly :)

**Comment by stprograms** [comment]
> Hi! I'm currently building a new dashboard app based on the SuSoDevs one and your project.

Maybe interesting for you, I also have developed an Arduino library that parses the input from the bus and calls callbacks if full telegrams and data is received. Would that be of use for your dashboard?
